---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: staging
  labels:
    app: seq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        image: datalust/seq:latest
        imagePullPolicy: IfNotPresent
        name: seq
        ports:
          - containerPort: 80
        resources: {}
        volumeMounts:
          - name: seq-data
            mountPath: /data
          - name: tz-karachi
            mountPath: /etc/localtime
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: seq-data
          hostPath:
            path: /mnt/psw/seq-data
        - name: tz-karachi
          hostPath:
            path: /usr/share/zoneinfo/Asia/Karachi

---
apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: seq
  ports:
    - name: "5341"
      port: 5341
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: seq-svc
  labels:
    app: seq
spec:
  type: NodePort
  selector:
    app: seq
  ports:
    - name: http
      port: 5341
      targetPort: 80
      nodePort: 30012
